### ISSUE TITLE
reduced chi2 calculation

### ISSUE THREAD

**Issue by johnarban** [astrofrog/sedfitter#33]
for determining the chi_2 per datapoint (options 'E' and 'F'), `FitInfo.keep()` uses `source.n_wav` to determine the number of data points, instead of `n_data`. Since the fitting is only constrained by `n_data` points, should not the chi_2 be calculated using `souce.n_data` instead of `souce.n_wav`?

**Comment by astrofrog** [comment]
@johnarban - indeed this was incorrect, I have fixed it in https://github.com/astrofrog/sedfitter/pull/49 - sorry for the long delay!
