### ISSUE TITLE
Two test failures on a fresh install

### ISSUE THREAD

**Issue by tomr-stargazer** [astrofrog/sedfitter#35]
Hi all,

I just cloned & installed SEDfitter and had two test failures.

Versions:

```
Python 2.7.11 :: Anaconda 2.2.0 (x86_64)
astropy : '1.0.5'
numpy : '1.10.0'
```

Test failures:

```
➜  sedfitter git:(master) python setup.py test
running test
running build
running build_py
============================= test session starts ==============================
platform darwin -- Python 2.7.11 -- pytest-2.2.4
collected 149 items

sedfitter/convolved_fluxes/tests/test_convolved_fluxes.py ................................F............
sedfitter/extinction/tests/test_extinction.py ............................F
sedfitter/filter/tests/test_filter.py .................
sedfitter/sed/tests/test_cube.py ..
sedfitter/sed/tests/test_sed.py ................
sedfitter/source/tests/test_source.py ..............................
sedfitter/tests/test_full_pipeline.py ........
sedfitter/utils/tests/test_parfile.py ..
```

The following gist contains the specific test failure tracebacks:
https://gist.github.com/tomr-stargazer/6d7ec04755352ed6ca8d

The failures look like this:
`E   ValueError: bad marshal data (unknown type code)`
and
`E                   UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)`

Just a heads-up!

**Comment by astrofrog** [comment]
I'm going to close this since I haven't seen these errors for a while, but feel free to re-open if you are still seeing them.
