### ISSUE TITLE
Not able to download the models

### ISSUE THREAD

**Issue by watsonv** [astrofrog/sedfitter#36]
Hi,

I have not been able to download the models from the links at http://sedfitter.readthedocs.org/en/stable/common_model_packages.html or via wget.  Getting "Error in server response."

Thanks,
Watson

**Comment by astrofrog** [comment]
@watsonv - it looks like it is working now, so it must have been a temporary issue. If you are still seeing it, it could be a problem with your connection - in that case, could you try from a different network?

**Comment by watsonv** [comment]
Hi Thomas,

Thank you for the reply.  I could download the models using a different
connection (using a guest network from the same office).  I checked with
our system administrator; copying his reply below:

"I suspect some kind of routing problem, probably on their end. I can
download it easily to an EAO machine, but not to UKIRT machines. I can't
think of any reason why that would be, since downloads from other sites
work normally."

So it looks like eao.hawaii.edu is able to download.  So, perhaps
ukirt.hawaii.edu is somehow denied access from your side (I was trying from
the ukirt account first).

Regards,
Watson

On Thu, Feb 25, 2016 at 9:23 AM, Thomas Robitaille <notifications@github.com
