### ISSUE TITLE
Parameter MENV

### ISSUE THREAD

**Issue by astroswag** [astrofrog/sedfitter#41]
I am not getting the MENV (mass of envelope) parameter in the output file.
I see from the header of the parameter.fits file that the keyword for this does not
exist. 

Can someone suggest what to modify in order to retreive this parameter?

**Comment by astrofrog** [comment]
@astroswag - please email me and I can send you a file which contains MENV (unless I already did!)

**Comment by drrklein** [comment]
What about the MENV for the new models from the 2017 paper?
