### ISSUE TITLE
Stellar Photosphere model

### ISSUE THREAD

**Issue by astroswag** [astrofrog/sedfitter#42]
Can anyone suggest how to get the stellar photosphere model (the dashed line in the online version)?
Anything to be modified in the fitting code?

**Comment by astrofrog** [comment]
We should include a new option in the ``plot`` function for this - contributions welcome! (I don't have a large amount of time to work on this these days)

**Comment by astrofrog** [comment]
I'm closing this since there is already a feature request open for this here: https://github.com/astrofrog/sedfitter/issues/15
