### ISSUE TITLE
Test Python SED Fitter

### ISSUE THREAD

**Issue by peteroffsapientia** [astrofrog/sedfitter#45]
After installing with 
-pip install sedfitter
i tried to test run with 
-python setup.py test
i keep getting errors like: ERROR collecting sedfitter/utils/tests/test_parfile.py
and i'm also told Python should be installed as a framework.

Please how do i fix this?

**Comment by astrofrog** [comment]
@peteroffsapientia - there is no easy way currently to test an installed version of the sedfitter. To run tests, you should instead just do:

```
git clone http://github.com/astrofrog/sedfitter
cd sedfitter
python setup.py test
```
