### ISSUE TITLE
SED fit output

### ISSUE THREAD

**Issue by basriaz** [astrofrog/sedfitter#46]
Hello,

  I'm using the command-line version of the SED fitting tool. After getting a fit, I can make the SED plot with the command :

```python
plot('output.fitinfo', 'plots_seds', select_format=('F', 3))
```

 Is it possible to plot the individual stellar, disk, envelope fluxes along with the total flux in the SED fit? I couldn't find the command for it in the explanation for the plot() function.

 Also, is it possible to save as ascii the total flux and the stellar, disk, envelope fluxes ?

Thanks,
Basmah

**Comment by astrofrog** [comment]
@basriaz - sorry for the delay! The SED fitter doesn't have access to the separate SED components unfortunately, because  these are not stored in the model packages distributed for the SED fitter.

**Comment by basriaz** [comment]
Hi Thomas,

 When I run the HO-CHUNK code, it writes in the output a Tmidplane.dat file
that has the disk midplane temperature profile. Is it possible to output
the temperature and density profiles of the envelope component?

Cheers,
Basmah
